<?php

namespace App\Helpers;

class HanyUpload extends AdminImageUpload
{
    /*
    public function getSize($size){
       parent::getSize(20,30);
       $this->size = $size;
    }
    */

    public function UploadOne($request, $sendArr = array(),$hany)
{
   return parent::UploadOne($request, $sendArr); // TODO: Change the autogenerated stub
}

}
